### ISSUE TITLE
Smithing 스킬 보너스 미적용 이슈

### ISSUE THREAD

**Issue by JohnFlashpoint** [Nope0525/Qwerty-Modpack#6]
금속 단조 시 스킬에 따른 내구도 보너스가 적용되지 않습니다.
기타 내구도를 조정하는 수식어 모드와의 충돌일 가능성이 있지만 어디까지나 추측입니다.
중요한 버그입니다.

**Comment by Qwerty0525** [comment]
어디가 어떻게 문제인지를 몰라서 해결불가, 해결부분을 계속 찾는중입니다

**Comment by Qwerty0525** [comment]
내구도 보너스가 아니라 다른 방향으로 보너스가 적용되는걸 확인했습니다
